# Generated by Django 3.0.3 on 2021-03-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Photo', models.ImageField(max_length=200, upload_to='category/')),
                ('Other', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=70)),
                ('Othername', models.TextField(default='', max_length=200)),
                ('Photo', models.ImageField(max_length=200, upload_to='product/')),
                ('Price', models.IntegerField(default='', max_length=1000)),
                ('Discount', models.IntegerField(default=0, max_length=100)),
                ('Quantity', models.CharField(default='', max_length=10)),
                ('Dprice', models.FloatField(default=0)),
            ],
        ),
    ]
