# Generated by Django 3.0.3 on 2021-04-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210307_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Status',
            field=models.CharField(default='available', max_length=20),
        ),
    ]
