# Generated by Django 3.0.3 on 2021-04-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_products_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Status',
            field=models.CharField(default='Available', max_length=20),
        ),
    ]
