# Generated by Django 3.0.3 on 2021-04-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210418_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Status',
        ),
    ]
