# Generated by Django 3.0.3 on 2021-03-07 17:21

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.DateField(blank=True)),
                ('To', models.DateField()),
                ('DT', models.DateTimeField(blank=True)),
                ('Content', models.TextField(default='', max_length=900)),
                ('Title', models.CharField(default='', max_length=500)),
                ('Type', models.CharField(default='', max_length=100)),
                ('Discount', models.IntegerField(default=0)),
                ('Limit', models.IntegerField(default=0)),
                ('Item', models.CharField(default=0, max_length=100)),
                ('How', models.IntegerField(default=0)),
                ('Free', models.CharField(default='', max_length=100)),
                ('Freenum', models.IntegerField(default=0)),
                ('Status', models.CharField(default='not_seen', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('bill_no', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=40)),
                ('Customer', models.CharField(default='', max_length=40)),
                ('Email', models.CharField(default='', max_length=50)),
                ('Phone', models.IntegerField(default=0, max_length=10)),
                ('Address', models.CharField(default='', max_length=100)),
                ('Pin', models.IntegerField(default=0, max_length=6)),
                ('State', models.CharField(default='', max_length=40)),
                ('City', models.CharField(default='', max_length=50)),
                ('order', picklefield.fields.PickledObjectField(default={}, editable=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Free', picklefield.fields.PickledObjectField(default={}, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(default='', max_length=20)),
                ('Image', models.ImageField(max_length=200, upload_to='blockbuster/')),
                ('Url', models.URLField(default='')),
            ],
        ),
    ]
