# Generated by Django 3.0.3 on 2021-03-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='Pin',
            field=models.IntegerField(default=0),
        ),
    ]
