# Generated by Django 3.0.3 on 2021-03-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_auto_20210307_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='Url',
        ),
        migrations.AddField(
            model_name='series',
            name='Search',
            field=models.CharField(default='', max_length=200),
        ),
    ]
