# Generated by Django 3.0.3 on 2021-03-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_auto_20210309_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='Name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
