# Generated by Django 3.0.3 on 2021-03-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0006_bill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Name',
            field=models.CharField(default='RPM', max_length=3),
        ),
    ]
