# Generated by Django 3.0.3 on 2021-04-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0007_auto_20210311_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadedlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=40)),
                ('Phone', models.IntegerField(default=0)),
                ('Address', models.CharField(default='', max_length=100)),
                ('Pin', models.IntegerField(default=0)),
                ('State', models.CharField(default='', max_length=40)),
                ('City', models.CharField(default='', max_length=50)),
                ('Date', models.DateField(auto_now_add=True)),
                ('ImageList', models.ImageField(upload_to='list/')),
            ],
        ),
    ]
