# Generated by Django 3.0.3 on 2021-04-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0008_uploadedlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='Content',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
