# Generated by Django 3.0.3 on 2021-04-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0009_auto_20210412_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='id',
        ),
        migrations.AddField(
            model_name='notifications',
            name='not_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
