# Generated by Django 3.0.3 on 2021-04-18 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0012_notifications_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='Status',
        ),
    ]
